# Site settings
title: Cabinet Dentaire Barthélémy
# if you want to preview the website under name.github.io/mysite, you have to
# change baseurl to /mysite
baseurl: ""
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [vendor, node_modules, Gemfile, Gemfile.lock, package.json, README.md]

# Site settings
settings:
  appointment_url: https://rdv.dentagest.ch/fr/#/gid/2950529C8B2A3B49BA560E071C62E157/cid/1A148EBC4A283C4ABA0585714744F9D6/step/1
  navigation:
    - home
    - team
    - treatments
    - pictures
    - costs
    - job
    - contact
  languages:
    - fr
    - en
  copyright: Cabinet Dentaire Barthélémy SA
  address: |
    Rue Juste-Olivier 8
    1260 Nyon, Suisse
  gps:
    lat: 46.3837699
    lng: 6.2359417
  email: mail@dentistebarthelemy.ch
  phone: +41 22 363 11 00
  fax: +41 22 363 11 02
  opening:
    monday: 8h - 19h
    tuesday: 7h30 - 17h
    wednesday: 7h30 - 17h
    thursday: 7h30 - 17h
    friday: 8h - 17h
    saturday: 8h - 13h
